spring:
  datasource:
    driver-class-name: "org.sqlite.JDBC"
    url: "jdbc:sqlite:D:\\luta_mysql_binlog_helper.db"
    username: ""
    password: ""
    maxActive: 1
    initialSize: 1

server:
  port: 18081

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: io.github.vimisky.luta.mysql.binlog.helper.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    name: "D:\\luta_mysql_binlog_helper.txt"
  level:
    root: info