spring:
  datasource:
    driver-class-name: "org.sqlite.JDBC"
    url: "jdbc:sqlite:luta_mysql_binlog_helper.db"
    username: ""
    password: ""
    maxActive: 1
    initialSize: 1
server:
  port: 18081
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: io.github.vimisky.luta.mysql.binlog.helper.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    name: "./luta-mysql-binlog-helper.log"
  level:
    root: info
  logback:
    rollingpolicy:
      max-history: 7
      total-size-cap: 10GB
      max-file-size: 1GB